# Generated by Django 5.2.12 on 2026-03-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='route_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='sms_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='provider_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(db_index=True, default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['user', 'route_date'], name='assignments_user_id_cbf7b9_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['user', 'sms_status'], name='assignments_user_id_0f31a7_idx'),
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['user', 'purpose', 'is_used'], name='email_otps_user_id_83455e_idx'),
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['code', 'is_used'], name='email_otps_code_c58ee5_idx'),
        ),
    ]
