# Generated by Django 5.2.12 on 2026-04-01 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_code', models.CharField(max_length=50)),
                ('dsp', models.CharField(blank=True, max_length=255, null=True)),
                ('transporter_id', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_name_raw', models.CharField(max_length=255)),
                ('route_progress', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('delivery_service_type', models.CharField(choices=[('AMZL', 'Amazon Logistics'), ('DSP', 'Delivery Service Partner'), ('LINEHAUL', 'Linehaul')], default='DSP', max_length=20)),
                ('route_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('all_stops', models.PositiveIntegerField(default=0)),
                ('stops_completed', models.PositiveIntegerField(default=0)),
                ('not_started_stops', models.PositiveIntegerField(default=0)),
                ('match_status', models.CharField(choices=[('matched', 'Matched'), ('unmatched', 'Unmatched'), ('ambiguous', 'Ambiguous')], db_index=True, default='unmatched', max_length=20)),
                ('match_notes', models.TextField(blank=True, null=True)),
                ('sms_status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('sent', 'Sent'), ('failed', 'Failed'), ('blocked', 'Blocked')], db_index=True, default='pending', max_length=20)),
                ('route_date', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'daily_routes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('matched_rows', models.PositiveIntegerField(default=0)),
                ('unmatched_rows', models.PositiveIntegerField(default=0)),
                ('ambiguous_rows', models.PositiveIntegerField(default=0)),
                ('ready_for_sms_rows', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'import_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='driver',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assignment',
            name='all_stops',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assignment',
            name='delivery_service_type',
            field=models.CharField(choices=[('AMZL', 'Amazon Logistics'), ('DSP', 'Delivery Service Partner'), ('LINEHAUL', 'Linehaul')], default='DSP', max_length=20),
        ),
        migrations.AddField(
            model_name='assignment',
            name='dsp_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='not_started_stops',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assignment',
            name='route_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='route_progress',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='assignment',
            name='transporter_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='dsp',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='transporter_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['user', 'transporter_id'], name='drivers_user_id_93b57e_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['user', 'dsp'], name='drivers_user_id_15fe67_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['user', 'phone'], name='drivers_user_id_0ad202_idx'),
        ),
        migrations.AddField(
            model_name='dailyroute',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_routes', to='api.driver'),
        ),
        migrations.AddField(
            model_name='dailyroute',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_routes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='smslog',
            name='daily_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='api.dailyroute'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyroute',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='api.importbatch'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['user', '-created_at'], name='import_batc_user_id_afc89c_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyroute',
            index=models.Index(fields=['user', 'batch'], name='daily_route_user_id_31f8f1_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyroute',
            index=models.Index(fields=['user', 'match_status'], name='daily_route_user_id_ad11f1_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyroute',
            index=models.Index(fields=['user', 'sms_status'], name='daily_route_user_id_63c8b2_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyroute',
            index=models.Index(fields=['user', 'route_date'], name='daily_route_user_id_5a1172_idx'),
        ),
    ]
